# This is a basic workflow to help you get started with Actions

name: Build EXE application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Sets environent variables for the complete workflow
env:
  REPO_PATH: 'D:\a\Windows_All-In-One_Tool\Windows_All-In-One_Tool'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}+1" >> $GITHUB_ENV
          echo "REPO_PATH=D:\a\Windows_All-In-One_Tool\Windows_All-In-One_Tool" >> $GITHUB_ENV


      # Converts the batch file into an executable program for Windows
      - name: Build BAT to EXE application
        run: |
          "%REPO_PATH%\Bat.exe" /bat "%REPO_PATH%\src\Windows All-In-One Tool.bat" /exe "%REPO_PATH%\src\Windows All-In-One Tool.exe" /icon "" /uac-admin /productversion "${{ env.RELEASE_VERSION }}" /internalname "Windows All-In-One Tool"
        shell: cmd

      - uses: actions/upload-artifact@v3
        with:
         name: Windows All-In-One Tool
         path: "src/Windows All-In-One Tool.exe"
