# This is a basic workflow to help you get started with Actions

name: Build EXE application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get version
        run: echo "version=$(git describe --tags --abbrev=0 # 0.1.0-dev)+1" >> $GITHUB_OUTPUT
        id: project
        
      - name: Tell current version
        run: echo The current version is ${{ steps.project.outputs.version }}

      # Converts the batch file into an executable program for Windows
      - name: Build BAT to EXE application
        run: |
         "D:\a\Windows_All-In-One_Tool\Windows_All-In-One_Tool\Bat.exe" /bat "D:\a\Windows_All-In-One_Tool\Windows_All-In-One_Tool\src\Windows All-In-One Tool.bat" /exe "D:\a\Windows_All-In-One_Tool\Windows_All-In-One_Tool\src\Windows All-In-One Tool.exe"
         "%windir%\system32\cmd.exe" /icon "" /uac-admin /productversion "${{ steps.project.outputs.version }}" /internalname "Windows All-In-One Tool"
        shell: cmd

      - uses: actions/upload-artifact@v3
        with:
         name: Windows All-In-One Tool
         path: "src/Windows All-In-One Tool.exe"
