name: Sync batch file
on:
 push:
 schedule:
 - cron: '0 * * * *'
 workflow_dispatch:
jobs:
 sync:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4

  - name: Download the file
    run: |
      curl -L '${{ secrets.onedrive_url }}' \
        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0' \
        -H 'Accept: application/json' \
        -H 'Accept-Language: nl-nl' \
        -H 'Referer: https://onedrive.live.com/' \
        -H 'Origin: https://onedrive.live.com' \
        -H 'Sec-Fetch-Dest: empty' \
        -H 'Sec-Fetch-Mode: cors' \
        -H 'Sec-Fetch-Site: cross-site' \
        -H 'Authorization: bearer ${{ secrets.authtoken }}' \
        -H 'Connection: keep-alive' \
        -H 'TE: trailers' \
        --output-dir src \
        -o Windows_All-In-One_Tool.bat

  - name: Push changes with Git
    run: |
      git config --global user.name "github-actions[bot]"
      git config --global user.email "github-actions[bot]@users.noreply.github.com"
      git pull
      git add .
      git commit -am "Auto-sync Windows_All-In-One_Tool.bat"
      git push origin ${{ github.ref_name }}
