name: Sync batch file
on:
 push:
 schedule:
 - cron: '0 * * * *'
 workflow_dispatch:
jobs:
 sync:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  
  - name: Download a file
    uses: valitydev/action-download-file@v1.0.6
    with:
     url: ${{ secrets.onedrive_url }}
     target-path: src/
