# This is a basic workflow to help you get started with Actions

name: Update from OneDrive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
   - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Sets environent variables for the complete workflow
env:
  REPO_PATH: 'D:\a\Windows_All-In-One_Tool\Windows_All-In-One_Tool'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Get file from OneDrive
        run: |
          Invoke-WebRequest -Uri 'https://freakinsoftmania-my.sharepoint.com/personal/admin_freakinsoftmania_unaux_com/_layouts/15/download.aspx?UniqueId=e44c4bad%2D3a2a%2D4904%2Dbc4e%2D1ce5e04ae0c0' -OutFile '$REPO_PATH\src\Windows All-In-One Tool.bat'
